### ISSUE TITLE
Показ мест

### ISSUE THREAD

**Issue by Traveler59** [omega-code/place-selector#2]

**Comment by AndreyTsvetkov** [comment]
Не уверен, что она закрыта, если pull request с ней не приехал в develop. А его пока и вовсе не было:)

**Comment by Traveler59** [comment]
Да, конечно, это же общие issues, а не свои для каждой ветки. Хорошо.

**Comment by AndreyTsvetkov** [comment]
Причем нам лучше делать мелкие задачи и частые PR, чем долгие. По описанию, если показываются и выбираются — это уже вполне объем для PR, если что. Не настаиваю прямо сейчас, может еще какие мелочи, но в целом не очень много должно еще войти до ближайшего PR. 

И напоминаю про необходимость привязывать коммиты к задачам вот так #4
